<script>
window.onload = function() {
    setTimeout(function() {
        window.print();
    }, 450); 
};
</script>
@extends('layouts.mainLayouts')

@section('content')
<style>
.print-container {
    max-width: 800px;
    margin: 0 auto;
    background: #fff;
    color: #000;
    padding: 40px;
    font-family: Arial, sans-serif;
}
.print-title {
    font-size: 24px;
    font-weight: bold;
    text-align: center;
    margin-bottom: 10px;
}
.print-date {
    text-align: center;
    margin-bottom: 20px;
}
.print-section-title {
    font-weight: bold;
    margin-top: 20px;
    margin-bottom: 5px;
}
.print-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px;
}
.print-table th, .print-table td {
    border: 1px solid #000;
    padding: 6px 8px;
    font-size: 14px;
}
.print-table th {
    background: #f0f0f0;
}
@media print {
    .no-print,
    .logo,
    .navbar,
    .sidebar,
    header,
    footer,
    .main-header,
    .main-sidebar,
    .main-footer,
    .brand-link,
    .brand-image,
    img[alt*="Metland"]:not(.print-container *),
    img[src*="logo"]:not(.print-container *),
    img[src*="metland"]:not(.print-container *),
    img[src*="/logo"]:not(.print-container *),
    img[src*="/metland"]:not(.print-container *),
    img[alt^="M"]:not(.print-container *),
    .app-logo {
        display: none !important;
        visibility: hidden !important;
        height: 0 !important;
        width: 0 !important;
        position: absolute !important;
        top: -9999px !important;
        left: -9999px !important;
    }
    body { background: #fff !important; }
}
</style>
<div class="print-container">
    <div class="no-print print-action-bar" style="text-align:right; margin-bottom:10px; position:relative; z-index:9999;">
        <button onclick="window.print()" class="btn btn-primary" style="z-index:10000; pointer-events:auto;">Print</button>
        <a href="{{ url()->previous() }}" class="btn btn-secondary" style="z-index:10000; pointer-events:auto;">Back</a>
    </div>
    <div class="print-title">Minutes Of Meeting</div>
    <div class="print-date">{{ \Carbon\Carbon::parse($header->NOTULEN_TRANS_DATETIME)->format('d F Y') }}</div>
    <div class="print-section-title">Participant :</div>
    <ol>
        @foreach($attendance as $a)
            <li>{{ $a->NOTULEN_ATTENDANCE_NAME }}@if($a->NOTULEN_ATTENDANCE_LEVEL) - {{ $a->NOTULEN_ATTENDANCE_LEVEL }}@endif</li>
        @endforeach
    </ol>
    <div class="print-section-title">Point Of Meeting :</div>
    <table class="print-table">
        <thead>
            <tr>
                <th style="width:5%">No</th>
                <th style="width:25%">Title</th>
                <th>Point</th>
                <th style="width:20%">PIC</th>
            </tr>
        </thead>
        <tbody>
            @foreach($details as $i => $d)
                <tr>
                    <td>{{ $i+1 }}</td>
                    <td>{{ $d->NOTULEN_DETAIL_TITLE }}</td>
                    <td>{!! $d->NOTULEN_DETAIL_DESC !!}</td>
                    <td>
                        @php
                            $pic = $attendance->firstWhere('NOTULEN_ATTENDANCE_ID', $d->NOTULEN_ATTENDANCE_ID);
                        @endphp
                        {{ $pic ? $pic->NOTULEN_ATTENDANCE_NAME : '' }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div style="margin-top:40px; font-size:12px; text-align:right;">
        Generated by Metland Support System
    </div>
</div>
<!-- print preview manual print only -->
@endsection
